// <auto-generated />
using KlassyCafePostgreSql.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlassyCafePostgreSql.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240824111946_migration_1")]
    partial class migration_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AboutId"));

                    b.Property<string>("AboutDescription")
                        .HasColumnType("text");

                    b.Property<string>("AboutImage1")
                        .HasColumnType("text");

                    b.Property<string>("AboutImage2")
                        .HasColumnType("text");

                    b.Property<string>("AboutImage3")
                        .HasColumnType("text");

                    b.Property<string>("AboutImage4")
                        .HasColumnType("text");

                    b.Property<string>("AboutLink")
                        .HasColumnType("text");

                    b.Property<string>("AboutTitle")
                        .HasColumnType("text");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Banner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BannerId"));

                    b.Property<bool>("BannerApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("BannerImage")
                        .HasColumnType("text");

                    b.Property<int>("BannerRow")
                        .HasColumnType("integer");

                    b.Property<string>("BannerSubTitle")
                        .HasColumnType("text");

                    b.Property<string>("BannerTitle")
                        .HasColumnType("text");

                    b.HasKey("BannerId");

                    b.ToTable("Banners");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("CategoryApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoryImage")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .HasColumnType("text");

                    b.Property<int>("CategoryRow")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Mail", b =>
                {
                    b.Property<int>("MailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MailId"));

                    b.Property<string>("MailHost")
                        .HasColumnType("text");

                    b.Property<string>("MailName")
                        .HasColumnType("text");

                    b.Property<string>("MailNickname")
                        .HasColumnType("text");

                    b.Property<string>("MailPassword")
                        .HasColumnType("text");

                    b.Property<int>("MailPort")
                        .HasColumnType("integer");

                    b.Property<bool>("MailSsl")
                        .HasColumnType("boolean");

                    b.HasKey("MailId");

                    b.ToTable("Mails");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<bool>("MenuApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("MenuImage")
                        .HasColumnType("text");

                    b.Property<decimal>("MenuPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MenuRow")
                        .HasColumnType("integer");

                    b.Property<string>("MenuSubTitle")
                        .HasColumnType("text");

                    b.Property<string>("MenuTitle")
                        .HasColumnType("text");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<bool>("ProductApproval")
                        .HasColumnType("boolean");

                    b.Property<string>("ProductName")
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProductRow")
                        .HasColumnType("integer");

                    b.Property<string>("ProductSubTitle")
                        .HasColumnType("text");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationId"));

                    b.Property<string>("ReservationBody")
                        .HasColumnType("text");

                    b.Property<string>("ReservationDate")
                        .HasColumnType("text");

                    b.Property<string>("ReservationEmail")
                        .HasColumnType("text");

                    b.Property<string>("ReservationFullname")
                        .HasColumnType("text");

                    b.Property<int>("ReservationPerson")
                        .HasColumnType("integer");

                    b.Property<string>("ReservationPhone")
                        .HasColumnType("text");

                    b.Property<string>("ReservationTime")
                        .HasColumnType("text");

                    b.HasKey("ReservationId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Product", b =>
                {
                    b.HasOne("KlassyCafePostgreSql.DAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("KlassyCafePostgreSql.DAL.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
